- name: Install and Configure NGINX Web Server
  hosts: nginx
  gather_facts: no
  vars:
    - domain: "test.local"
  tasks:
    - name: Install nginx
      ansible.builtin.apt:
        name: nginx
        state: present

    - name: Enable service nginx, and not enabled
      ansible.builtin.service:
        name: nginx
        enabled: yes

    # this has bug causing to fail as of this writing
    - name: Start service nginx, if not started
      ansible.builtin.service:
        name: nginx
        state: started
      ignore_errors: yes

    # alternative to start service
    - name: Populate service facts
      service_facts:

    - name: Start service nginx, if not started
      ansible.builtin.shell: service nginx start
      when: ansible_facts.services.nginx.state != 'running'

    - name: copy nginx site.conf
      template:
        src: site.conf.j2
        dest: /etc/nginx/sites-enabled/{{ domain }}
        owner: root
        group: root
        mode: "0644"
      notify: restart nginx

  handlers:
    # this has bug causing to fail as of this writing
    - name: Restart service nginx
      service:
        name: nginx
        state: restarted
      ignore_errors: yes

    # alternative to start service
    - name: Restart service nginx
      ansible.builtin.shell: service nginx restart
